// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5xvwkXDwYM1dKX5EEWJjbpLxGDsW2T8g',
    appId: '1:39223626542:web:7c6ab3fe521dfff28a88bf',
    messagingSenderId: '39223626542',
    projectId: 'social-media-app-auth-eaf69',
    authDomain: 'social-media-app-auth-eaf69.firebaseapp.com',
    storageBucket: 'social-media-app-auth-eaf69.firebasestorage.app',
    measurementId: 'G-NRTEMYK23N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxN7DZFpTPD_A-ePEzVURH6gNdpX6rHoI',
    appId: '1:39223626542:android:edc6d64e335fb7a38a88bf',
    messagingSenderId: '39223626542',
    projectId: 'social-media-app-auth-eaf69',
    storageBucket: 'social-media-app-auth-eaf69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqNLepD2wO6rhsoLWhDKvJQ9iyk5p_muc',
    appId: '1:39223626542:ios:f7ec255fca18a79d8a88bf',
    messagingSenderId: '39223626542',
    projectId: 'social-media-app-auth-eaf69',
    storageBucket: 'social-media-app-auth-eaf69.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqNLepD2wO6rhsoLWhDKvJQ9iyk5p_muc',
    appId: '1:39223626542:ios:f7ec255fca18a79d8a88bf',
    messagingSenderId: '39223626542',
    projectId: 'social-media-app-auth-eaf69',
    storageBucket: 'social-media-app-auth-eaf69.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5xvwkXDwYM1dKX5EEWJjbpLxGDsW2T8g',
    appId: '1:39223626542:web:d9a8c918315d33b38a88bf',
    messagingSenderId: '39223626542',
    projectId: 'social-media-app-auth-eaf69',
    authDomain: 'social-media-app-auth-eaf69.firebaseapp.com',
    storageBucket: 'social-media-app-auth-eaf69.firebasestorage.app',
    measurementId: 'G-642TL241PK',
  );
}
